app = 'gemini-z'
primary_region = 'sin'

[env]
  TZ = "Asia/Shanghai"
  ENABLE_STORAGE = "true"

[http_service]
  internal_port = 7860
  force_https          = true
  auto_start_machines  = true
  auto_stop_machines   = false
  min_machines_running = 1
  processes            = ["app"]

  [http_service.concurrency]
    type       = "requests"
    soft_limit = 9999
    hard_limit = 9999

[[mounts]]
  source      = "gemini_data"
  destination = "/hajimi/settings"
